version: "3.8"

services:
  api:
    build: .
    ports:
      - "5006:5006"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      MONGO_URI: "mongodb://mongo:27017/TripShare"

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
